### ISSUE TITLE
Any ETA for Apple Watch support?

### ISSUE THREAD

**Issue by blocman** [twofas/2fas-ios#16]
Apple Watch is fundamental to how I use my 2FA apps, I’d switch to yours immediately if it were added. Any ETA? Or whether it’s in the works at all?

**Comment by adocyn** [comment]
Hi @blocman, yes, it's in the "pipeline", we have to just do one thing before that - add password based encryption for iCloud content. Then we can implement that in the Watch app from the start and skip messy transition between old and new storage format. In the long run it's the quicker way. But because of that I can't give you an ETA. Q2 - Q3.

**Comment by cthulu** [comment]
Does this mean the format will not be compatible anymore with Android? Or, you can always export it in a platform-agnostic format?

**Comment by adocyn** [comment]
@cthulu Exported JSON file is an entirely different beast than the CloudKit storage database. It won't be impacted 👍
