### ISSUE TITLE
4.5.0 layout issue with token list on iPad Mini

### ISSUE THREAD

**Issue by valynor** [twofas/2fas-ios#27]
iPad Mini 5, iOS 16.6

Before the update to 4.5.0 the iPad Mini in portrait orientation with the sidebar enabled would show one vertical row of tokens on the right side - perfect. 

Now it shows 2 rows in the token list, with the left row partially hidden behind the sidebar. You have to tap away the sidebar for half of the tokens being usable. Would be nice if you could fix that.

**Comment by adocyn** [comment]
Hi @valynor, we've just fixed it by making the menu/sidebar behave in a standard, "system way" and also by increasing the density of  information on iPad Mini and other iPads, as this was highly requested. The menu/sidebar is visible on start but once closed, will stay closed until the app is terminated, so that shouldn't be a problem.

**Comment by valynor** [comment]
The problem is it shows up every time you open the app, so you have to click it away every time. That's just bad UI/UX IMHO. 
At least make it remember the last state it was in, please.

**Comment by enzor00** [comment]
That's right, it's annoying

**Comment by adocyn** [comment]
@valynor @enzor00 thanks for your feedback! The idea here was that it should be easily discoverable by less technically savvy users, but yeah, remembering the state will fix that on both sides. I'll try to add it in upcoming 5.0 version 👍

**Comment by adocyn** [comment]
@valynor @enzor00 5.0 will remember sidebar state.
