### ISSUE TITLE
it seems iCloud backup is on by default?

### ISSUE THREAD

**Issue by jsomedon** [twofas/2fas-ios#29]
If so, why not make it off by default?

**Comment by adocyn** [comment]
@jsomedon Hi, it's on by default because most users don't bother to enable it, but as soon as something goes wrong, they're are looking for help because they can't login. It's the first rule about backup that you don't ever need it until you do, but then it's too late. And this strategy works - less technically savvy users are grateful, that e.g. they replaced the phone and codes are still there.

**Comment by jsomedon** [comment]
I see, that makes sense. :+1:
