### ISSUE TITLE
Feature Request: interactable Widget

### ISSUE THREAD

**Issue by chillSeCdW** [twofas/2fas-ios#56]
It would be awesome to copy my tokens when pressing on the entry of the widget. Currently this just opens the app, where I have to search for the Entry and copy it from there.

**Comment by adocyn** [comment]
@chillSeCdW Hi, widgets (fixes for iOS 17 and probably some interactivity) are queued for 5.3. We're currently working on 5.2 so it will take some time.

**Comment by adocyn** [comment]
We've implemented the interaction for widgets but it's very limited. The idea was to copy to Pasteboard from within the widgets but it's not possible, because of a security measure on iOS side. Simply put - we can't access that resource from within the widget "app". So we're opening the 2FAS app, like the tap on widgets would, but there's a "copy token" action associated with that. Not ideal, but best we can do with this limited functionality.
