### ISSUE TITLE
Import from Twilio Authy

### ISSUE THREAD

**Issue by baschny** [twofas/2fas-ios#76]
As an Authy user facing the discontinuation of the Authy Desktop App (for MacOS), I will give 2FAS a try together with the Browser extension. I noted that there are "Import Tokens" available for several other apps (Aegis, Raivo OTP, LastPass, Google Auth, andOTP and Authenticator Pro), but not Authy.

Is there any technical chance to have this available?

Expect a huge influx of disappointed Authy users in the next coming weeks, since the discontinuation of the Desktop App which was previously announced for August 2024 (see https://support.authy.com/hc/en-us/articles/17592416719003-Authy-for-Desktop-End-of-Life-EOL), was suddenly advanced to March 19, 2024 according to their inline help in the latest (and probably last??) update.

Also a native MacOS App would also be cool (seems to be in the works in #36) - that was the main reason for me using Authy (sync between mobile device and desktop). I even used their Windows App on my PC.

**Comment by baschny** [comment]
Argh, I guess this answers my question already: https://support.authy.com/hc/en-us/articles/1260805179070-Export-or-Import-Tokens-in-the-Authy-app - so probably no workaround possible then to get the original QR-Codes or create new ones for each individual site.

**Comment by gillbates** [comment]
thx, I also migrated from authy to 2fas today

**Comment by SensehacK** [comment]
I was able to achieve this [following this guide by AlexTech01](https://github.com/AlexTech01/Authy-iOS-MiTM) and at the end I had to improvise in order to massage the exported data according to 2Fas - Import option called "Ravio-OTP" 

Which I have quickly shared my findings here [Authy Migration on iOS](https://gist.github.com/SensehacK/48c36efd582d6bab3d0bebcb46968f5b)

Import works fine with iOS 2Fas app, using Authy iOS app, Charles proxy (MiTM), python scripts. 
March 2025.
